In [10]:
import numpy as np
import cv2
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
 
image = cv2.imread("test1.png")
grayImage = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
 
faces = face_cascade.detectMultiScale(grayImage)
 
print(type(faces))
 
if len(faces) == 0:
    print ("No faces found")
 
else:
    print (faces)
    print (faces.shape)
    print ("Number of faces detected: " + str(faces.shape[0]))
 
    for (x,y,w,h) in faces:
        cv2.rectangle(image,(x,y),(x+w,y+h),(0,255,0),1)
 
    cv2.rectangle(image, ((0,image.shape[0] -25)),(270, image.shape[0]), (255,255,255), -1)
    cv2.putText(image, "Number of faces detected: " + str(faces.shape[0]), (0,image.shape[0] -10), cv2.FONT_HERSHEY_TRIPLEX, 0.5,  (0,0,0), 1)
 
    cv2.imshow('Image with faces',image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

<class 'numpy.ndarray'>
[[600 582  34  34]
 [308 222  55  55]
 [192 211  57  57]
 [436 237  52  52]
 [689 242  56  56]
 [341 122  51  51]
 [206 129  53  53]
 [561 274  54  54]
 [616  81  83  83]
 [469 134  53  53]
 [587 136  53  53]
 [801 137  55  55]
 [702 136  54  54]]
(13, 4)
Number of faces detected: 13
